#RegistrationPage Elements Locator
firstName_Locator="id:inputFirstName"
lastname_Locator="id:inputLastName"
email_Locator="id:inputEmail"
phone_Locator="id:inputPhone"
companyName_Locator="id:inputCompanyName"
streetAddress_Locator="id:inputAddress1"
countrycodeList_Locator="xpath://div[@class='selected-dial-code']"
city_Locator="id:inputCity"
registerButton_Locator="xpath://*[@value='Register']"